feat: supports redirecting to a specified page after successful login
halo-sigs/plugin-oauth2 pull request #33
Opened 2023-06-02 07:46 UTC by guqing

### What this PR does?
登录成功后支持跳转到指定页面

/kind feature

Fixes #23 

```release-note
登录成功后支持跳转到指定页面
```

2023-06-12 06:40 UTC, ruibaby reviewed
/lgtm

2023-06-13 02:12 UTC, JohnNiang requested changes

2023-06-13 02:12 UTC, JohnNiang commented on src/main/java/run/halo/oauth/Oauth2Authenticator.java
> +                .defaultIfEmpty(URI.create("/console/dashboard"))
默认情况下，重定向到 `/console` 即可。

2023-06-13 02:12 UTC, JohnNiang commented on src/main/java/run/halo/oauth/Oauth2LoginConfiguration.java
> +    static class QueryParamRedirectServerAuthenticationSuccessHandler implements ServerAuthenticationSuccessHandler {
这个类似乎没有被用到。

2023-06-13 03:06 UTC, guqing commented on src/main/java/run/halo/oauth/Oauth2LoginConfiguration.java
> +    static class QueryParamRedirectServerAuthenticationSuccessHandler implements ServerAuthenticationSuccessHandler {
good catch, 忘记删了🫡

2023-07-03 03:13 UTC, ruibaby reviewed
/lgtm

2023-07-03 03:14 UTC, guqing commented
/cc @halo-sigs/halo

2023-07-03 04:15 UTC, JohnNiang commented on src/main/java/run/halo/oauth/Oauth2Authenticator.java
> +                                                    Authentication authentication,
`authentication` 似乎没有用到。

2023-07-03 06:55 UTC, JohnNiang requested changes

2023-07-03 06:55 UTC, JohnNiang commented on src/main/java/run/halo/oauth/Oauth2Authenticator.java
> +                                                    Authentication authentication,
这里的 `authentication` 参数似乎也没有使用到。

2023-07-03 07:43 UTC, JohnNiang approved these changes
/lgtm

2023-07-03 07:44 UTC, merged